repos:

  # ----------------------------------------------------------------------------
  # Remote

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.1.0"
    hooks:
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-xml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v6.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

  # ----------------------------------------------------------------------------
  # Local

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        language: system
        types: [python]
        require_serial: true
        entry: poetry run flake8

  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        types: [python]
        require_serial: true
        entry: poetry run black

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        types: [python]
        require_serial: true
        pass_filenames: false
        entry: poetry run mypy .

  - repo: local
    hooks:
      - id: requirements
        name: requirements
        language: system
        files: "^poetry.lock$"
        pass_filenames: false
        entry: >-
          poetry export
          --format "requirements.txt"
          --output "requirements.txt"
          --without-hashes

  # ----------------------------------------------------------------------------

exclude: |
  (?x)(
    ^CHANGELOG.md$|
    ^coverage.xml$|
    ^poetry.lock$|
    ^requirements.txt$
  )
